"""Ports that isolate the core from external products."""

from collections.abc import Mapping, Sequence
from typing import Protocol

from workspace_orchestrator.models import Task, Workspace


class TaskProvider(Protocol):
    def create_task(self, requirement_id: str, task: Task) -> Task: ...
    def get_task(self, task_id: str) -> Task: ...
    def list_tasks(self, requirement_id: str) -> Sequence[Task]: ...
    def update_status(self, task_id: str, status: str) -> Task: ...
    def add_comment(self, task_id: str, body: str) -> None: ...
    def link_session(
        self,
        task_id: str,
        session_id: str,
        *,
        codex_project_id: str | None = None,
        codex_project_kind: str | None = None,
        codex_host_id: str | None = None,
        workspace_path: str | None = None,
    ) -> None: ...
    def set_git_context(
        self, task_id: str, branch: str | None = None, worktree: str | None = None
    ) -> None: ...


class AgentProvider(Protocol):
    def current_session_id(self) -> str | None: ...
    def build_context(self, workspace: Workspace) -> str: ...


class GitProvider(Protocol):
    def status(self) -> Mapping[str, object]: ...
    def current_branch(self) -> str | None: ...
    def create_branch(self, name: str) -> None: ...
    def create_worktree(self, path: str, branch: str) -> None: ...
    def recent_commits(self, limit: int = 5) -> Sequence[str]: ...
    def diff(self) -> str: ...


class KnowledgeProvider(Protocol):
    def search(self, query: str) -> Sequence[str]: ...
    def preserve(self, title: str, body: str, sources: Sequence[str]) -> str: ...
