"""AI Dev OS Requirement 控制面的无构建浏览器界面。"""

DASHBOARD_HTML = r"""<!doctype html>
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>AI Dev OS · Requirement 控制面</title>
<style>
:root{--bg:#070b14;--panel:#0d1320;--panel2:#111a2a;--line:#202c40;--text:#edf3ff;--muted:#8fa1bc;--cyan:#45d7c2;--blue:#6d8cff;--purple:#ad7bff;--green:#55d68b;--yellow:#f5bd58;--red:#ff6b7a;--radius:16px}
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:radial-gradient(circle at 12% 0,#122440 0,transparent 28%),var(--bg);color:var(--text);font:14px/1.5 Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif}button,input,textarea,select{font:inherit}button{cursor:pointer}.hidden{display:none!important}.sr-only{position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip:rect(0,0,0,0);white-space:nowrap;border:0}:focus-visible{outline:3px solid #6d8cffaa;outline-offset:2px}
.login{min-height:100vh;display:grid;place-items:center;padding:24px}.login-card{width:min(430px,100%);padding:34px;border:1px solid var(--line);border-radius:24px;background:rgba(13,19,32,.94);box-shadow:0 30px 90px #0009}.brand{display:flex;align-items:center;gap:12px;font-weight:750;letter-spacing:.02em}.logo{width:36px;height:36px;border-radius:11px;display:grid;place-items:center;background:linear-gradient(135deg,var(--cyan),var(--blue));color:#07101b;font-weight:900;box-shadow:0 0 28px #45d7c244}.login h1{font-size:27px;margin:28px 0 8px}.login p{color:var(--muted);margin:0 0 22px}.field{width:100%;padding:13px 14px;border:1px solid var(--line);border-radius:11px;color:var(--text);background:#090e18;outline:0}.field:focus{border-color:var(--blue);box-shadow:0 0 0 3px #6d8cff22}.primary{border:0;border-radius:11px;padding:12px 18px;color:#061019;background:linear-gradient(135deg,var(--cyan),#80e9cf);font-weight:750}.login .primary{width:100%;margin-top:12px}.error{color:var(--red);min-height:22px;margin-top:10px!important}
.shell{min-height:100vh;display:grid;grid-template-columns:238px 1fr}.sidebar{position:sticky;top:0;height:100vh;border-right:1px solid var(--line);background:#090e18dd;backdrop-filter:blur(18px);padding:22px 16px;display:flex;flex-direction:column}.sidebar .brand{padding:0 8px 24px}.nav{display:grid;gap:6px}.nav button{border:0;background:transparent;color:var(--muted);padding:11px 12px;text-align:left;border-radius:10px;display:flex;gap:11px;align-items:center}.nav button:hover,.nav button.active{color:var(--text);background:#172238}.nav button.active{box-shadow:inset 3px 0 var(--cyan)}.side-foot{margin-top:auto;padding:14px 10px;color:var(--muted);border-top:1px solid var(--line)}.live-dot{display:inline-block;width:8px;height:8px;border-radius:50%;background:var(--green);box-shadow:0 0 10px var(--green);margin-right:8px}.logout{border:0;background:transparent;color:var(--muted);padding:8px 0;margin-top:8px}
.main{min-width:0}.topbar{position:sticky;top:0;z-index:5;display:flex;justify-content:space-between;gap:20px;align-items:center;padding:18px 28px;border-bottom:1px solid var(--line);background:#070b14d9;backdrop-filter:blur(18px)}.crumb{font-size:12px;color:var(--muted)}.topbar h1{font-size:19px;margin:3px 0 0}.top-actions{display:flex;align-items:center;gap:10px}.pill{display:inline-flex;align-items:center;gap:7px;padding:5px 9px;border:1px solid var(--line);border-radius:999px;color:var(--muted);font-size:12px}.pill.good{color:var(--green);border-color:#55d68b44;background:#55d68b0e}.content{padding:24px 28px 48px;max-width:1500px;margin:auto}.view{display:none}.view.active{display:block}.section-head{display:flex;justify-content:space-between;align-items:end;gap:16px;margin:0 0 14px}.section-head h2{font-size:16px;margin:0}.section-head p{color:var(--muted);margin:3px 0 0;font-size:12px}
.hero{padding:24px;border:1px solid #2d3c56;border-radius:20px;background:linear-gradient(115deg,#111c30,#0d1422 58%,#10231f);margin-bottom:18px;position:relative;overflow:hidden}.hero:after{content:"";position:absolute;width:260px;height:260px;border-radius:50%;right:-100px;top:-140px;background:#45d7c21a;filter:blur(4px)}.hero h2{font-size:25px;margin:2px 0 8px}.hero p{margin:0;color:var(--muted);max-width:880px}.eyebrow{color:var(--cyan);font-size:11px;font-weight:800;letter-spacing:.12em;text-transform:uppercase}
.stats{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;margin-bottom:20px}.stat,.card{border:1px solid var(--line);background:linear-gradient(160deg,var(--panel2),var(--panel));border-radius:var(--radius)}.stat{padding:16px}.stat .label{color:var(--muted);font-size:12px}.stat strong{display:block;font-size:24px;margin-top:5px}.stat small{color:var(--muted)}.grid{display:grid;grid-template-columns:minmax(0,1.7fr) minmax(300px,1fr);gap:16px}.card{padding:17px;min-width:0}.card h3{font-size:14px;margin:0}.muted{color:var(--muted)}
.phases{display:grid;gap:9px;margin-top:14px}.phase{border:1px solid var(--line);border-radius:12px;background:#0a101c;overflow:hidden}.phase-main{width:100%;border:0;color:inherit;background:transparent;text-align:left;display:grid;grid-template-columns:42px minmax(0,1fr) auto;align-items:center;gap:10px;padding:11px 12px;cursor:pointer}.phase-index{width:34px;height:34px;border-radius:10px;display:grid;place-items:center;background:#182337;color:var(--muted);font-weight:800}.phase.passed .phase-index{background:#55d68b18;color:var(--green)}.phase.active{border-color:#6d8cff66;box-shadow:0 0 0 1px #6d8cff22}.phase.active .phase-index{background:#6d8cff22;color:#9fb1ff}.phase-title{font-weight:700}.phase-meta{font-size:11px;color:var(--muted)}.status{font-size:11px;padding:4px 8px;border-radius:99px;border:1px solid var(--line);white-space:nowrap}.status.passed,.status.completed,.status.cancelled{color:var(--green);background:#55d6a00d}.status.active,.status.delivered{color:#9fb1ff;background:#6d8cff12}.status.blocked,.status.failed{color:var(--red);background:#ff6b7a10}.status.queued,.status.in_progress{color:var(--yellow);background:#f5bd5810}.phase-details{display:none;border-top:1px solid var(--line);padding:10px 12px}.phase.open .phase-details{display:block}.acceptance{display:grid;gap:7px}.acceptance div{display:flex;gap:8px;color:var(--muted);font-size:12px}.check{color:var(--green)}
.list{display:grid;gap:9px;margin-top:14px}.list-item{padding:11px;border:1px solid var(--line);border-radius:11px;background:#0a101b}.list-item strong{font-size:12px}.list-item p{color:var(--muted);margin:5px 0 0;font-size:12px;overflow-wrap:anywhere}.split{display:flex;justify-content:space-between;gap:10px;align-items:center}.sha{font:11px ui-monospace,SFMono-Regular,Consolas,monospace;color:#aab9d1}.notice{padding:12px;border-left:3px solid var(--yellow);background:#f5bd580d;color:#e8d8b4;border-radius:8px;margin-top:12px}.notice.good{border-color:var(--green);background:#55d68b0b;color:#bce9cc}
.agent-layout{display:grid;grid-template-columns:340px minmax(0,1fr);gap:16px;min-height:650px}.agent-list{display:grid;gap:8px;margin-top:14px;max-height:720px;overflow:auto}.agent{width:100%;border:1px solid var(--line);border-radius:12px;background:#0a101b;color:var(--text);padding:12px;text-align:left}.agent:hover,.agent.selected{border-color:#6d8cff88;background:#131d31}.agent-top{display:flex;justify-content:space-between;gap:8px}.agent-id{font:11px ui-monospace,SFMono-Regular,Consolas,monospace;color:var(--muted);white-space:nowrap;overflow:hidden;text-overflow:ellipsis;margin-top:6px}.agent-detail{display:flex;flex-direction:column;min-height:650px}.conversation{display:flex;flex-direction:column;gap:12px;overflow:auto;padding:16px 4px;min-height:420px;max-height:590px}.message{max-width:82%;padding:11px 13px;border-radius:14px;background:#172136;border:1px solid #26344c;white-space:pre-wrap;overflow-wrap:anywhere}.message.user{align-self:flex-end;background:#23335c;border-color:#395185}.message.agent{align-self:flex-start}.message.tool{align-self:flex-start;background:#101925;color:#b5c4db;font:12px ui-monospace,monospace}.message .who{display:block;color:var(--muted);font-size:10px;margin-bottom:5px}.composer{margin-top:auto;border-top:1px solid var(--line);padding-top:14px}.composer textarea{width:100%;min-height:94px;resize:vertical;padding:12px;border:1px solid var(--line);border-radius:12px;color:var(--text);background:#080d17;outline:0}.composer-foot{display:flex;justify-content:space-between;gap:9px;align-items:center;margin-top:9px}.composer-foot span{font-size:11px;color:var(--muted)}.composer-actions{display:flex;gap:8px;align-items:center}.composer select{padding:10px;border:1px solid var(--line);border-radius:10px;color:var(--text);background:#080d17}.command-actions{display:flex;gap:6px;margin-top:8px}.command-actions button{padding:5px 8px;border:1px solid var(--line);border-radius:8px;background:#111b2b;color:var(--text)}
.filters{display:flex;gap:7px;flex-wrap:wrap}.filter{border:1px solid var(--line);border-radius:99px;background:#0d1422;color:var(--muted);padding:6px 10px}.filter.active{color:var(--text);border-color:#6d8cff88;background:#6d8cff17}.events{display:grid;gap:8px;margin-top:14px}.event{display:grid;grid-template-columns:88px 120px minmax(0,1fr) 150px;gap:12px;padding:11px 12px;border:1px solid var(--line);border-radius:10px;background:#0a101a;align-items:start}.event-kind{text-transform:uppercase;font-size:10px;letter-spacing:.08em;color:var(--cyan)}.event-main{overflow-wrap:anywhere}.event-time{font-size:11px;color:var(--muted);text-align:right}.event-session{font:10px ui-monospace,monospace;color:var(--muted);white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.receipt-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px;margin-top:14px}.receipt{padding:13px;border:1px solid var(--line);border-radius:12px;background:#0a101b}.receipt p{color:var(--muted);font-size:11px;margin:7px 0}.git-lines{display:grid;gap:8px;margin-top:14px}.git-line{display:flex;justify-content:space-between;gap:12px;padding-bottom:8px;border-bottom:1px solid var(--line)}.git-line:last-child{border:0}.empty{text-align:center;color:var(--muted);padding:50px 20px}.spinner{width:16px;height:16px;border:2px solid #ffffff33;border-top-color:white;border-radius:50%;display:inline-block;animation:spin .8s linear infinite}@keyframes spin{to{transform:rotate(360deg)}}
.space-grid{margin-top:16px}.facts{display:grid;gap:9px;margin-top:12px}.fact{padding:10px;border:1px solid var(--line);border-radius:10px;background:#0a101b;overflow-wrap:anywhere}.fact b{display:block;font-size:11px;color:var(--cyan);margin-bottom:4px}.task-node{display:grid;grid-template-columns:minmax(120px,1fr) minmax(0,2fr) auto;gap:10px;align-items:center;padding:10px;border:1px solid var(--line);border-radius:10px;background:#0a101b}.detail-facts{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px;margin-top:12px}.detail-facts .fact{min-width:0}.raw-event{font:11px ui-monospace,monospace;white-space:pre-wrap;overflow-wrap:anywhere;color:#b5c4db}.detail-section{margin-top:14px}.detail-section h4{margin:0 0 7px;color:var(--muted);font-size:11px;text-transform:uppercase;letter-spacing:.08em}
@media(max-width:980px){.shell{grid-template-columns:76px 1fr}.sidebar .brand span,.nav button span,.side-foot span,.logout{display:none}.sidebar{padding:18px 10px}.sidebar .brand{justify-content:center;padding:0 0 20px}.nav button{justify-content:center;font-size:18px}.stats{grid-template-columns:repeat(2,1fr)}.grid,.agent-layout{grid-template-columns:1fr}.agent-list{max-height:300px}.receipt-grid{grid-template-columns:1fr}}
@media(max-width:640px){.shell{display:block}.sidebar{position:fixed;z-index:10;left:0;right:0;bottom:0;top:auto;width:auto;height:64px;border:0;border-top:1px solid var(--line);padding:7px 10px}.sidebar .brand,.side-foot{display:none}.nav{grid-template-columns:repeat(4,1fr)}.nav button{padding:8px}.main{padding-bottom:70px}.topbar{padding:14px 16px}.top-actions .pill:first-child{display:none}.content{padding:16px}.stats{gap:8px}.stat{padding:13px}.stat strong{font-size:20px}.event{grid-template-columns:70px 1fr}.event-session,.event-time{display:none}.hero{padding:18px}.hero h2{font-size:21px}}
</style>
</head>
<body>
<section id="login" class="login"><div class="login-card"><div class="brand"><div class="logo">A</div><span>AI Dev OS</span></div><h1>连接 Requirement 控制面</h1><p>输入本机生成的访问 Token。Token 仅保存在当前浏览器会话中。</p><label class="sr-only" for="token">访问 Token</label><input id="token" class="field" type="password" autocomplete="off" placeholder="访问 Token"><button class="primary" onclick="connect()">安全连接</button><p id="login-error" class="error" role="status" aria-live="polite"></p></div></section>
<div id="app" class="shell hidden">
  <aside class="sidebar"><div class="brand"><div class="logo">A</div><span>AI Dev OS</span></div><nav class="nav" aria-label="控制面导航">
    <button class="active" data-view="overview" onclick="showView('overview')">⌂ <span>Requirement</span></button>
    <button data-view="agents" onclick="showView('agents')">◉ <span>Agents</span></button>
    <button data-view="events" onclick="showView('events')">⌁ <span>Events</span></button>
    <button data-view="evidence" onclick="showView('evidence')">✓ <span>Verification</span></button>
  </nav><div class="side-foot"><div><i class="live-dot"></i><span>实时连接</span></div><button class="logout" onclick="logout()">断开并清除 Token</button></div></aside>
  <main class="main"><header class="topbar"><div><div class="crumb">REQUIREMENT CONTROL PLANE</div><h1 id="top-title">正在读取…</h1></div><div class="top-actions"><span id="sync-time" class="pill">等待同步</span><span id="connection" class="pill good"><i class="live-dot"></i>在线</span></div></header>
  <div class="content">
    <section id="overview" class="view active"><div id="hero"></div><div id="stats" class="stats"></div><div class="grid"><div class="card"><div class="section-head"><div><h2>交付阶段</h2><p>Gate 事实决定阶段状态；点击阶段查看验收项</p></div></div><div id="phases" class="phases"></div></div><div><div class="card"><div class="section-head"><div><h2>当前阻塞与下一步</h2><p>来自 Requirement Workspace</p></div></div><div id="actions"></div></div><div class="card" style="margin-top:16px"><div class="section-head"><div><h2>Git 状态</h2><p>当前隔离工作树</p></div></div><div id="git-mini"></div></div></div></div><div class="grid space-grid"><div class="card"><div class="section-head"><div><h2>Intent / Acceptance / Progress</h2><p>Requirement Space 的稳定事实</p></div></div><div id="requirement-facts"></div></div><div class="card"><div class="section-head"><div><h2>Main Agent</h2><p>持久 Owner 状态与下一动作</p></div></div><div id="main-agent"></div></div></div><div class="card space-grid"><div class="section-head"><div><h2>Task Graph</h2><p>Task 与一等 Execution 的关系</p></div></div><div id="task-graph" class="facts"></div></div></section>
    <section id="agents" class="view"><div class="section-head"><div><h2>Execution / Agent / Session</h2><p>点击 Execution 查看模型、状态、耗时及完整事件分类</p></div></div><div class="agent-layout"><div class="card"><h3>Active Agents / Executions</h3><div id="agent-list" class="agent-list"></div></div><div class="card agent-detail"><div id="agent-header"></div><div id="conversation" class="conversation" aria-live="polite"></div><div id="composer" class="composer"><label for="message">向所选 Agent 发送指令</label><textarea id="message" maxlength="8192" placeholder="向所选 Codex Runtime 发送消息…"></textarea><div class="composer-foot"><span>只读沙箱 · 审批拒绝 · 8192 字符</span><div class="composer-actions"><label class="sr-only" for="delivery">投递方式</label><select id="delivery"><option value="auto">自动投递</option><option value="queue">排队下一条</option><option value="new_turn">新 Turn</option><option value="steer">Steer 当前 Turn</option></select><button id="send" class="primary" onclick="sendMessage()">发送</button></div></div><div id="send-result" class="muted" role="status" aria-live="polite" style="margin-top:8px"></div></div></div></div></section>
    <section id="events" class="view"><div class="section-head"><div><h2>实时 Event Plane</h2><p>Append-only 事件增量；页面缓存可随时重建</p></div><div id="event-filters" class="filters"></div></div><div id="event-list" class="events"></div></section>
    <section id="evidence" class="view"><div class="grid"><div class="card"><div class="section-head"><div><h2>Verification Receipts</h2><p>最近结构化验证证据</p></div></div><div id="receipts" class="receipt-grid"></div></div><div class="card"><div class="section-head"><div><h2>Repository</h2><p>精确 Git 投影</p></div></div><div id="git-full"></div><div class="section-head" style="margin-top:22px"><div><h2>Command Queue</h2><p>持久化且幂等的用户指令</p></div></div><div id="commands" class="list"></div></div></div></section>
  </div></main>
</div>
<script>
const state={data:null,events:new Map(),executionDetails:new Map(),cursor:0,view:'overview',selectedAgent:null,eventFilter:'all',loading:false,pendingReply:null};
const $=id=>document.getElementById(id); const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function authHeaders(){return {'Authorization':'Bearer '+$('token').value,'Content-Type':'application/json'}}
async function api(path,options={}){const response=await fetch(path,{...options,headers:{...authHeaders(),...(options.headers||{})}});let payload={};try{payload=await response.json()}catch{}if(!response.ok)throw Error(payload.error?.message||payload.error||payload.result||`HTTP ${response.status}`);return payload}
async function connect(){sessionStorage.setItem('ai-dev-os-token',$('token').value);$('login-error').textContent='正在连接…';try{await refresh(true);$('login').classList.add('hidden');$('app').classList.remove('hidden');$('login-error').textContent=''}catch(error){$('login-error').textContent='连接失败：'+error.message}}
function logout(){sessionStorage.removeItem('ai-dev-os-token');location.reload()}
function showView(view){state.view=view;document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id===view));document.querySelectorAll('.nav button').forEach(x=>x.classList.toggle('active',x.dataset.view===view))}
function fmt(value){if(!value)return '—';const date=new Date(value);return Number.isNaN(date.valueOf())?esc(value):date.toLocaleString('zh-CN',{hour12:false})}
function short(value,n=10){return value?esc(String(value).slice(0,n)):'—'}
function statusLabel(value){const labels={passed:'已通过',active:'执行中',running:'运行中',starting:'启动中',waiting:'等待恢复',pending:'待处理',blocked:'阻塞',completed:'已完成',failed:'失败',cancelled:'已取消',queued:'排队',delivered:'已投递',in_progress:'进行中',idle:'空闲'};return labels[value]||value||'未知'}
function status(value){return `<span class="status ${esc(value)}">${esc(statusLabel(value))}</span>`}
async function refresh(initial=false){if(state.loading)return;state.loading=true;try{const data=await api('api/status?after='+(initial?0:state.cursor));state.data=data;(data.events||[]).forEach(event=>state.events.set(event.event_id,event));state.cursor=Math.max(state.cursor,data.next_cursor||0);render();$('connection').innerHTML='<i class="live-dot"></i>在线';$('connection').className='pill good';$('sync-time').textContent='同步 '+new Date().toLocaleTimeString('zh-CN',{hour12:false})}catch(error){if(initial)throw error;$('connection').textContent='已断线';$('connection').className='pill';}finally{state.loading=false}}
function activePhase(){return (state.data.projection?.phases||[]).find(p=>p.status==='active')}
function render(){const d=state.data,w=d.workspace,p=d.projection||{},meta=w.meta||{},phases=p.phases||[],agents=allAgents();$('top-title').textContent=`${d.requirement_id} · ${meta.title||''}`;const phase=activePhase();$('hero').innerHTML=`<div class="hero"><div class="eyebrow">Requirement Space · source of truth</div><h2>${esc(meta.title||d.requirement_id)}</h2><p>${esc(firstParagraph(w.requirement)||'Requirement 控制面')}</p><div style="margin-top:15px;display:flex;gap:8px;flex-wrap:wrap">${status(meta.status)}<span class="pill">${phase?`权威阶段 Phase ${phase.phase}`:'等待阶段激活'}</span><span class="pill">${esc(meta.task_provider||'本地')} Task Provider</span></div></div>`;const passed=phases.filter(x=>x.status==='passed').length,activeExecutions=(p.executions||[]).filter(x=>['queued','starting','running','waiting'].includes(x.status)).length,blocked=(p.blockers||[]).length;$('stats').innerHTML=stat('当前阶段',phase?`Phase ${phase.phase}`:'—',phase?.title||p.requirement_space?.phase||'无激活阶段')+stat('阶段门禁',`${passed} / ${phases.length}`,`${phases.length-passed} 个尚未通过`)+stat('活动 Execution',activeExecutions,`${(p.executions||[]).length} 个 Execution`)+stat('阻塞项',blocked,blocked?'需要处理':'当前无显式阻塞');renderPhases(phases);renderActions(p);renderGit(p.git||{});renderRequirementFacts(p.requirement_space||{});renderMainAgent(p.main_agent);renderTaskGraph(p.task_graph||{},p.execution_graph||{});renderAgents(agents);renderConversation();renderEvents();renderReceipts(p.verification||[]);renderCommands(d.commands||[])}
function stat(label,value,note){return `<div class="stat"><span class="label">${esc(label)}</span><strong>${esc(value)}</strong><small>${esc(note)}</small></div>`}
function firstParagraph(md){const text=(md||'').split('\n').map(x=>x.trim()).filter(x=>x&&!x.startsWith('#')&&!x.startsWith('- '))[0];return text||''}
function renderPhases(phases){$('phases').innerHTML=phases.map(p=>`<div class="phase ${esc(p.status)}" id="phase-${p.phase}"><button class="phase-main" aria-expanded="false" aria-controls="phase-details-${p.phase}" onclick="togglePhase(this)"><div class="phase-index">${p.phase}</div><div><div class="phase-title">${esc(p.title)}</div><div class="phase-meta">${esc(p.task_id||'')} · ${p.passed_acceptance}/${p.total_acceptance} 验收项</div></div>${status(p.status)}</button><div id="phase-details-${p.phase}" class="phase-details"><div class="acceptance">${(p.acceptance||[]).map(a=>`<div><span class="check">${a.status==='PASS'?'✓':'○'}</span><span><b>${esc(a.id)}</b> ${esc(a.description)}</span></div>`).join('')||'<span class="muted">暂无验收项</span>'}</div>${p.commit_sha?`<div class="sha" style="margin-top:10px">Gate SHA ${esc(p.commit_sha)}</div>`:''}</div></div>`).join('')}
function togglePhase(button){const opened=button.parentElement.classList.toggle('open');button.setAttribute('aria-expanded',String(opened))}
function renderActions(p){const blockers=p.blockers||[],next=p.next_actions||[];$('actions').innerHTML=(blockers.length?`<div class="notice"><b>阻塞</b>${blockers.map(x=>`<div>• ${esc(x)}</div>`).join('')}</div>`:'<div class="notice good"><b>当前没有显式阻塞</b></div>')+`<div class="list">${next.map(x=>`<div class="list-item"><strong>下一步</strong><p>${esc(x)}</p></div>`).join('')||'<div class="list-item muted">Workspace 尚未记录下一步</div>'}</div>`}
function renderRequirementFacts(space){const progress=space.progress||{},intent=Object.entries(space.intent||{}),acceptance=space.acceptance||[];$('requirement-facts').innerHTML=`<div class="facts"><div class="fact"><b>Goal</b>${esc(space.goal||'未记录')}</div><div class="fact"><b>Progress</b>${progress.executions_terminal||0}/${progress.executions_total||0} Execution 结束 · ${progress.acceptance_completed||0}/${progress.acceptance_total||0} 验收完成</div>${intent.map(([k,v])=>`<div class="fact"><b>${esc(k)}</b>${esc(v)}</div>`).join('')}<div class="fact"><b>Acceptance</b>${acceptance.map(x=>`${x.completed?'✓':'○'} ${esc(x.text)}`).join('<br>')||'未记录'}</div></div>`}
function renderMainAgent(owner){$('main-agent').innerHTML=owner?`${owner.stale?'<div class="notice">Main Agent 投影早于当前 Workspace 阶段，等待下一次 Observe。</div>':''}<div class="facts"><div class="fact"><b>Loop</b>${esc(owner.loop_stage)} · Cycle ${esc(owner.cycle)} · Revision ${esc(owner.revision)}</div><div class="fact"><b>Last observed phase</b>${esc(owner.current_phase)}</div><div class="fact"><b>Next actions</b>${(owner.next_actions||[]).map(esc).join('<br>')||'未记录'}</div><div class="fact"><b>Known risks</b>${(owner.known_risks||[]).map(esc).join('<br>')||'无'}</div></div>`:'<div class="empty">Main Agent 尚未建立持久状态</div>'}
function renderTaskGraph(tasks,executions){const taskRows=(tasks.nodes||[]).map(n=>`<div class="task-node"><strong>${esc(n.task_id)}</strong><span class="agent-id">Supervisor Task</span>${status(n.status)}</div>`).join(''),executionRows=(executions.nodes||[]).map(n=>`<div class="task-node"><strong>${esc(n.execution_id)}</strong><span class="agent-id">${esc(n.task_id)} · Execution</span>${status(n.status)}</div>`).join('');$('task-graph').innerHTML=`<div class="muted">Task Graph · ${esc(tasks.source||'supervisor')}</div>${taskRows||'<div class="fact">尚无 Supervisor Task 计划</div>'}<div class="muted" style="margin-top:8px">Execution Graph · ${esc(executions.source||'execution-store')}</div>${executionRows||'<div class="fact">尚无 Execution</div>'}`}
function gitRows(g){return [['分支',g.branch],['HEAD',g.head],['上游',g.upstream],['Ahead / Behind',`${g.ahead??'—'} / ${g.behind??'—'}`],['工作树',g.clean?'干净':'有修改']].map(([k,v])=>`<div class="git-line"><span class="muted">${esc(k)}</span><span class="sha">${esc(v??'—')}</span></div>`).join('')}
function renderGit(g){const html=g.error?`<div class="notice">${esc(g.error)}</div>`:`<div class="git-lines">${gitRows(g)}</div>${!g.clean?`<div class="notice">${(g.changes||[]).length} 个工作树变化；Dashboard 只读显示，不会修改 Git。</div>`:''}`;$('git-mini').innerHTML=html;$('git-full').innerHTML=html}
function allAgents(){const d=state.data,p=d.projection||{},executions=(p.executions||[]).map(e=>({...e,selection_id:`execution:${e.id}`,display_session_id:e.id,runtime:e.runtime_id,task_ids:[e.task_id],is_execution:true})),executionSessions=new Set(executions.map(x=>x.session_id).filter(Boolean)),sessions=(p.agents||[]).filter(x=>!executionSessions.has(x.session_id)).map(x=>({...x,selection_id:x.session_id}));return [{selection_id:'__remote__',session_id:'__remote__',display_session_id:d.remote_session_id||'首次发送时建立专用 Session',runtime:'codex',role:'Remote Runtime',status:d.connected&&d.session_id===d.remote_session_id?'active':'idle',task_ids:[d.workspace?.meta?.requirement_task_id].filter(Boolean),started_at:null},...executions,...sessions]}
function duration(value){if(value===null||value===undefined)return '—';const seconds=Number(value);if(seconds<60)return `${seconds}s`;if(seconds<3600)return `${Math.floor(seconds/60)}m ${seconds%60}s`;return `${Math.floor(seconds/3600)}h ${Math.floor((seconds%3600)/60)}m`}
function renderAgents(agents){if(!state.selectedAgent)state.selectedAgent='__remote__';$('agent-list').innerHTML=agents.map(a=>`<button class="agent ${a.selection_id===state.selectedAgent?'selected':''}" onclick="selectAgent('${esc(a.selection_id)}')"><div class="agent-top"><strong>${esc(a.is_execution?`${a.id} · ${a.role}`:a.role)}</strong>${status(a.status)}</div><div style="margin-top:5px">${esc(a.runtime)} · ${(a.task_ids||[]).map(esc).join(', ')||'未绑定 Task'}</div><div class="agent-id">${esc(a.display_session_id||a.session_id)}</div></button>`).join('')||'<div class="empty">暂无 Agent</div>';const selected=agents.find(x=>x.selection_id===state.selectedAgent),reply=state.executionDetails.get(state.selectedAgent)?.reply;$('agent-header').innerHTML=selected?(selected.is_execution?`<div class="split"><div><h3>${esc(selected.id)} · ${esc(selected.role)}</h3><div class="agent-id">${esc(selected.session_id||'尚无 Session')}</div></div>${status(selected.status)}</div><div class="detail-facts"><div class="fact"><b>Provider / Runtime</b>${esc(selected.provider)} / ${esc(selected.runtime_id)}</div><div class="fact"><b>Model / Reasoning</b>${esc(selected.model||'Provider 默认')} / ${esc(selected.reasoning_effort||'Provider 默认')}</div><div class="fact"><b>Task</b>${esc(selected.task_id)}</div><div class="fact"><b>Duration</b>${duration(selected.duration_seconds)}</div></div>${reply&&!reply.supported?`<div class="notice">无法从 Workbench 继续原 Session：${esc(reply.reason)}。${esc(reply.alternative)}</div>`:''}`:`<div class="split"><div><h3>${esc(selected.role)} · ${esc(selected.runtime)}</h3><div class="agent-id">${esc(selected.display_session_id||selected.session_id)}</div></div>${status(selected.status)}</div>`):'<h3>选择 Agent</h3>';const executionReady=selected?.is_execution&&reply?.supported;$('composer').classList.toggle('hidden',Boolean(selected?.is_execution&&!executionReady));$('delivery').classList.toggle('hidden',Boolean(selected?.is_execution));$('message').placeholder=selected?.is_execution?'继续该 Execution 的原生 Session…':state.selectedAgent==='__remote__'?'向专用 Codex Runtime 发送消息…':'向所选 Session 发送；忙时可 Steer 或排队';$('send-result').textContent=''}
async function selectAgent(id){state.selectedAgent=id;renderAgents(allAgents());renderConversation();if(id.startsWith('execution:')&&!state.executionDetails.has(id)){try{await loadExecution(id,0,false)}catch(error){state.executionDetails.set(id,{error:error.message});renderConversation()}}}
async function loadExecution(id,after,append){const executionId=id.slice('execution:'.length),page=await api(`api/executions/${encodeURIComponent(executionId)}?after=${after}&limit=100`),previous=state.executionDetails.get(id);if(append&&previous?.details){for(const key of ['conversation','tool_calls','files','diff','tests','errors','events'])page.details[key]=[...(previous.details[key]||[]),...(page.details[key]||[])];page.details.commands=previous.details.commands||[]}state.executionDetails.set(id,page);renderAgents(allAgents());renderConversation()}
async function loadMoreExecution(){const page=state.executionDetails.get(state.selectedAgent);if(page?.has_more)await loadExecution(state.selectedAgent,page.next_cursor,true)}
function itemText(item){if(item.text)return item.text;const content=item.content||[];return content.map(x=>x.text||x.output||JSON.stringify(x)).join('\n')||item.name||item.type||''}
function renderConversation(){const d=state.data,p=d.projection||{},execution=(p.executions||[]).find(x=>`execution:${x.id}`===state.selectedAgent);if(execution){const page=state.executionDetails.get(state.selectedAgent);if(!page){$('conversation').innerHTML='<div class="empty">正在按需加载 Execution Details…</div>';return}if(page.error){$('conversation').innerHTML=`<div class="notice">加载失败：${esc(page.error)}</div>`;return}const detail=page.details||{},sections=[['conversation','Conversation'],['tool_calls','Tool calls'],['commands','Commands · Session scoped'],['files','Files'],['diff','Diff'],['tests','Tests'],['errors','Errors'],['events','Events · Redacted Provider payload']];$('conversation').innerHTML=`<div class="notice">HTTP 安全视图会脱敏敏感字段；事件按页加载，Event Store 原始记录不变。</div>`+sections.map(([key,label])=>`<div class="detail-section"><h4>${label} · ${(detail[key]||[]).length}</h4>${(detail[key]||[]).map(item=>`<div class="message tool raw-event">${esc(item.event_id?JSON.stringify(item):`${item.status||''} ${item.message||''} ${item.result||''}`)}</div>`).join('')||'<div class="muted">无</div>'}</div>`).join('')+(page.has_more?`<button class="primary" onclick="loadMoreExecution()">加载下一页</button>`:`<div class="muted">已到事件末尾 · cursor ${esc(page.next_cursor)}</div>`);return}const remote=state.selectedAgent==='__remote__'||state.selectedAgent===d.session_id,detail=remote?(d.agent_detail||{}):{},groups=[['messages','message'],['tools','tool'],['file_changes','tool'],['verification','tool'],['approvals','tool']];let html='';for(const [name,fallback] of groups){for(const item of detail[name]||[]){const kind=item.role==='user'?'user':item.role==='agent'?'agent':fallback;html+=`<div class="message ${kind}"><span class="who">${kind==='user'?'用户':kind==='agent'?'Agent':esc(item.type)} · Turn ${short(item.turn_id,8)}</span>${esc(item.text||item.name||item.path||item.type)}</div>`}}if(!html)html=`<div class="empty">${remote?'该 Session 尚无规范化对话；发送后会显示消息、工具、文件、验证和审批':'该历史 Session 尚无可投影详情'}</div>`;$('conversation').innerHTML=html;$('conversation').scrollTop=$('conversation').scrollHeight}
function eventSummary(event){const payload=event.payload||{},params=payload.params||{},item=params.item||{},turn=params.turn||{};if(item.content)return itemText(item);if(params.delta)return params.delta;if(params.error?.message)return params.error.message;if(turn.status)return `Turn ${turn.status}`;return payload.method||JSON.stringify(payload)}
function renderEvents(){const kinds=['all',...new Set([...state.events.values()].map(x=>x.kind))];$('event-filters').innerHTML=kinds.map(k=>`<button class="filter ${state.eventFilter===k?'active':''}" onclick="setEventFilter('${esc(k)}')">${esc(k==='all'?'全部':k)}</button>`).join('');const events=[...state.events.values()].filter(x=>state.eventFilter==='all'||x.kind===state.eventFilter).sort((a,b)=>b.sequence-a.sequence).slice(0,250);$('event-list').innerHTML=events.map(e=>`<div class="event"><div class="event-kind">${esc(e.kind)}</div><div class="event-session">${esc(e.session_id||e.runtime_id)}</div><div class="event-main">${esc(eventSummary(e))}</div><div class="event-time">#${e.sequence} · ${fmt(e.timestamp)}</div></div>`).join('')||'<div class="empty">当前筛选没有事件</div>'}
function setEventFilter(kind){state.eventFilter=kind;renderEvents()}
function renderReceipts(receipts){$('receipts').innerHTML=receipts.map(r=>`<div class="receipt"><div class="split"><strong>${esc(r.suite_id||r.receipt_id)}</strong>${status((r.status||'').toLowerCase())}</div><p>${esc(r.summary||'无摘要')}</p><div class="split"><span class="sha">${short(r.commit_sha,9)}</span><span class="muted" style="font-size:10px">${fmt(r.completed_at)}</span></div></div>`).join('')||'<div class="empty">暂无 Verification Receipt</div>'}
function commandButtons(c){if(c.status==='failed')return `<button onclick="commandAction('${esc(c.command_id)}','retry')">重试</button>`;if(c.status==='queued')return `<button onclick="commandAction('${esc(c.command_id)}','deliver')">立即投递</button><button onclick="commandAction('${esc(c.command_id)}','cancel')">取消</button>`;if(c.status==='delivered')return `<button onclick="commandAction('${esc(c.command_id)}','cancel')">中断</button>`;return ''}
function renderCommands(commands){$('commands').innerHTML=[...commands].reverse().slice(0,20).map(c=>`<div class="list-item"><div class="split"><strong>${short(c.command_id,18)} · 第 ${c.attempt||1} 次</strong>${status(c.status)}</div><p>${esc(c.message)}</p>${c.result?`<p>↳ ${esc(c.result)}</p>`:''}<div class="command-actions">${commandButtons(c)}</div></div>`).join('')||'<div class="empty">暂无指令</div>'}
function selectedSession(){return state.selectedAgent==='__remote__'?'new-codex-session':state.selectedAgent}
async function sendMessage(){const text=$('message').value.trim();if(!text)return;const button=$('send'),delivery=$('delivery').value,isExecution=state.selectedAgent?.startsWith('execution:'),executionId=isExecution?state.selectedAgent.slice('execution:'.length):null,pending=state.pendingReply,commandId=isExecution&&pending?.selection===state.selectedAgent&&pending?.message===text?pending.commandId:crypto.randomUUID();if(isExecution)state.pendingReply={selection:state.selectedAgent,message:text,commandId};button.disabled=true;button.innerHTML='<i class="spinner"></i> 投递中';$('send-result').textContent=isExecution?'正在恢复原 Session…':delivery==='queue'?'正在写入持久队列…':'指令已发送，等待 Runtime…';try{const path=isExecution?`api/executions/${encodeURIComponent(executionId)}/message`:'api/message',payload=isExecution?{message:text,command_id:commandId}:{message:text,command_id:commandId,session_id:selectedSession(),delivery},result=await api(path,{method:'POST',body:JSON.stringify(payload)}),success=isExecution?`已继续原 Session ${short(result.session_id,12)} · Turn ${short(result.turn_id,12)}`:`${statusLabel(result.status)}：${result.result||result.command_id}`;$('message').value='';state.pendingReply=null;if(isExecution){state.executionDetails.delete(state.selectedAgent);try{await loadExecution(state.selectedAgent,0,false);$('send-result').textContent=success}catch(error){$('send-result').textContent=success+'；详情刷新失败：'+error.message}}else{await refresh(false);$('send-result').textContent=success}}catch(error){$('send-result').textContent='投递结果未确认：'+error.message+'；再次发送将复用同一 command_id'}finally{button.disabled=false;button.textContent='发送'}}
async function commandAction(id,action){try{const body=action==='retry'?JSON.stringify({retry_id:crypto.randomUUID()}):undefined;await api(`api/commands/${id}/${action}`,{method:'POST',body});await refresh(false)}catch(error){$('send-result').textContent='操作失败：'+error.message}}
$('token').value=sessionStorage.getItem('ai-dev-os-token')||'';$('token').addEventListener('keydown',event=>{if(event.key==='Enter')connect()});setInterval(()=>{if(!$('app').classList.contains('hidden'))refresh(false)},3000);if($('token').value)connect();
</script>
</body></html>"""
